kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubedoom
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 5900
    hostPort: 5900
    listenAddress: "127.0.0.1"
